const model = {
    'Day': 'Day',
    'Date': 'Date',
    'ConfirmedCases_Day': 'Confirmed Cases (Day)',
    'ImportedCase_Day': 'Imported Cases (Day)',
    'TotalLocalCase_Day': 'Total Local Cases (Day)',
    'LocalLinked': 'Local Linked Cases',
    'LocalUnlinked': 'Local Unlinked Cases',
    'Hospital_OtherAreas': 'Hospitalized - Other Areas',
    'HospitalizedTotal': 'Hospitalized - Total',
    'HospitalizedStable': 'Hospitalized - Stable',
    'HospitalizedICU': 'Hospitalized - ICU',
    'HospitalizedOtherArea': 'Hospitalized - Other Areas',
    'Recovered_Day': 'Recovered - Day',
    'Deaths_Day': 'Deaths - Day',
    'CumulativeConfirmed': 'Cumulative Confirmed',
    'CumulativeImported': 'Cumulative Imported',
    'CumulativeLocal': 'Cumulative Local',
    'CumulativeRecovered': 'Cumulative Recovered',
    'CumulativeDeaths': 'Cumulative Deaths',
    'CumulativeDischarged': 'Cumulative Discharged',
    'DailyQuarantineOrdersIssued': 'Daily Quarantine Orders (QUO) Issued',
    'TotalCloseContacts': 'Total Close Contacts',
    'Quarantined': 'Quarantined',
    'CompletedQuarantine': 'Completed Quarantine',
    'DORSCON': 'DORSCON Level',
    'QUO-Pending': 'QUO - Pending',
    'QUO-TransferHospital': 'QUO - Transfer Hospital',
    'QUO-NonGazettedDorm': 'QUO - Non Gazetted Dorms',
    'QUO-GazettedDorm': 'QUO - Gazetted Dorms',
    'QUO-GovtQuarantinedFacilities': 'QUO - Government Quarantine Facilities',
    'QUO-HomeQuarantinedOrder': 'QUO - Home Quarantine Orders',
    'Remarks': 'Remarks'
};

module.exports = model;