const model = {
    'Day': 'Day',
    'Date': 'Date',
    'ConfirmedCases_Day': 'Confirmed Cases (Day)',
    'ImportedCase_Day': 'Imported Cases (Day)',
    'TotalLocalCase_Day': 'Total Local Cases (Day)',
    'LocalLinked': 'Local Linked Cases',
    'LocalUnlinked': 'Local Unlinked Cases',
    'Hospital_OtherAreas': 'Hospitalized + Community Facilities',
    'HospitalizedTotal': 'Hospitalized (Total)',
    'HospitalizedStable': 'Hospitalized (Stable)',
    'HospitalizedICU': 'Hospitalized (ICU)',
    'HospitalizedOtherArea': 'In Community Facilities',
    'Recovered_Day': 'Recovered (Day)',
    'Deaths_Day': 'Deaths (Day)',
    'CumulativeConfirmed': 'Cumulative Confirmed',
    'CumulativeImported': 'Cumulative Imported',
    'CumulativeLocal': 'Cumulative Local',
    'CumulativeRecovered': 'Cumulative Recovered',
    'CumulativeDeaths': 'Cumulative Deaths',
    'CumulativeDischarged': 'Cumulative Discharged',
    'DailyQuarantineOrdersIssued': 'Daily Quarantine Orders (QUO) Issued',
    'TotalCloseContacts': 'Total Close Contacts',
    'Quarantined': 'Quarantined',
    'CompletedQuarantine': 'Completed Quarantine',
    'DORSCON': 'DORSCON Level',
    'QUO_Pending': 'QUO - Pending',
    'QUO_TransferHospital': 'QUO - Transfer Hospital',
    'QUO_NonGazettedDorm': 'QUO - Non Gazetted Dorms',
    'QUO_GazettedDorm': 'QUO - Pending Extension',
    'QUO_GovtQuarantinedFacilities': 'QUO - Government Quarantine Facilities',
    'QUO_HomeQuarantinedOrder': 'QUO - Home Quarantine Orders',
    'Remarks': 'Remarks',
    'SitRepLink': 'Situation Report PDF'
};

module.exports = model;