image: alpine:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

# GitLab-CI Security Scans
include:
  - template: SAST.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: Container-Scanning.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

sast:
  rules:
    - when: on_success

license_scanning:
  rules:
    - when: on_success

container_scanning:
  rules:
    - when: on_success

dependency_scanning:
  dependencies:
    - Install Node Dependencies
  rules:
    - when: on_success

eslint-sast:
  rules:
    - when: on_success

gemnasium-dependency_scanning:
  rules:
    - when: on_success

nodejs-scan-sast:
  rules:
    - when: on_success

retire-js-dependency_scanning:
  rules:
    - when: on_success

secrets-sast:
  rules:
    - when: on_success

# Workflow Default Settings
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

# Node.JS Testing
Install Node Dependencies:
  image: node:alpine
  stage: build
  script: npm i

# Build docker containers
Docker Master:
  # Official docker image.
  image: docker:latest
  stage: deploy
  dependencies:
    - Install Node Dependencies
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      when: always
    - when: never

Build Docker:
  # Official docker image.
  image: docker:latest
  stage: deploy
  dependencies:
    - Install Node Dependencies
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      when: never
    - when: always

Container Scan Docker:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# Deploy to heroku manually
Deploy to Heroku Prod:
  image: ruby:alpine
  stage: deploy
  dependencies:
    - Install Node Dependencies
  variables:
    MY_APP: ccn-covid19-sg-dashboard
  before_script:
    - apk add git curl
    - gem install dpl
    - echo "Deploying to Heroku"
  script: dpl --provider=heroku --app=$MY_APP --api-key=$HEROKU_KEY
  environment:
    name: Production
    url: https://covid19sg.itachi1706.com/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      when: manual
    - when: never
