tasks:
  - init: |
        sudo apt update
        sudo apt install -y python3 python3-dev
        sudo python3 -m ensurepip && sudo rm -r /usr/lib/python*/ensurepip
        sudo pip3 install --no-cache --upgrade pip setuptools wheel && if [ ! -e /usr/bin/pip ]; then sudo ln -s pip3 /usr/bin/pip ; fi 
        sudo apt install -y python2 python2-dev 
        npm install
    command: npm run start