name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  buildpush:
    runs-on: ubuntu-latest
    name: Build and Push to DockerHub Private
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: itachi1706/personal-docker-images:covid19-sg-dashboard
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/arm/v6
